services: 
  telegraf:
    container_name: telegraf
    image: telegraf:1.21.4-alpine
    depends_on:
      influxdb:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      tig-network: 
        ipv4_address: 192.168.1.2
  
  influxdb:
    container_name: influxdb
    image : influxdb:2.1.1
    restart: unless-stopped
    healthcheck:
      test: "curl -f http://influxdb:8086/health | grep pass"
      interval: 3s
      timeout: 10s
      retries: 5
    environment:
      - TZ=Asia/Bangkok
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=syslog
      - DOCKER_INFLUXDB_INIT_BUCKET=syslog-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=1234

    volumes:
      - ./influxdb/config:/etc/influxdb2
      - ./influxdb/data:/var/lib/influxdb2
    ports:
      - 8086:8086
    networks:
      tig-network: 
        ipv4_address: 192.168.1.3

# Default user ID is now 472 GID 0
  grafana:
    container_name: grafana
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    image: grafana/grafana:8.4.3
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provision:/etc/grafana
      - ./grafana/log:/var/log/grafana
    ports:
      - 3000:3000
    networks:
      tig-network: 
        ipv4_address: 192.168.1.4
  
  # UID 1001 GID 1002
  prometheus:
    container_name: prometheus
    restart: unless-stopped
    image: prom/prometheus:v2.34.0
    volumes : 
      - ./prometheus:/etc/prometheus/
    environment:
      - TZ=Asia/Bangkok
    ports:
      - 9090:9090
    networks:
      tig-network: 
        ipv4_address: 192.168.1.5

  push-gateway:
    container_name: push-gateway
    restart: unless-stopped
    image : prom/pushgateway:v1.4.2
    ports:
      - 9091:9091
    environment:
      - TZ=Asia/Bangkok
    networks:
      tig-network: 
        ipv4_address: 192.168.1.6

networks:
  tig-network:
    external:
      name: tig-network
